import { useEffect, useRef } from "react";
import { Alert, Animated, Pressable, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { usePlayer } from "@/lib/player-context";
import { loadGratitudeEntries, saveGratitudeEntries } from "@/lib/gratitude";
import { ensureDefaultPlaylist, savePlaylists } from "@/lib/playlists";

const colors = { background: "#F8F6F0", ink: "#163B2B", muted: "#7B8A82", primary: "#2F7D5A", soft: "#E1F0E8", orange: "#E9905E", surface: "#FFFFFF" };
export default function PlayerScreen() {
  const router = useRouter(); const { entries, currentIndex, isPlaying, settings, toggle, next, previous, hide } = usePlayer(); const current = entries[currentIndex]; const motion = useRef(new Animated.Value(0)).current;
  useEffect(() => { const loop = Animated.loop(Animated.sequence([Animated.timing(motion, { toValue: 1, duration: 3200, useNativeDriver: true }), Animated.timing(motion, { toValue: 0, duration: 3200, useNativeDriver: true })])); loop.start(); return () => loop.stop(); }, [motion]);
  if (!current) return <ScreenContainer containerClassName="bg-[#F8F6F0]" safeAreaClassName="bg-[#F8F6F0]"><View style={styles.empty}><Text style={styles.emptyTitle}>Henüz dinlenecek şükran yok</Text><Pressable onPress={() => router.back()} style={styles.backAction}><Text style={styles.backText}>Geri dön</Text></Pressable></View></ScreenContainer>;
  const closePlayer = () => { hide(); router.back(); };
  const addToPlaylist = async () => { const lists = await ensureDefaultPlaylist(); Alert.alert("Playlist seç", "Bu şükranı hangi playlist’e ekleyelim?", lists.map((list) => ({ text: list.name, onPress: async () => { const entries = await loadGratitudeEntries(); await saveGratitudeEntries(entries.map((entry) => entry.id === current.id ? { ...entry, favorite: true } : entry)); await savePlaylists(lists.map((item) => item.id === list.id ? { ...item, entryIds: item.entryIds.includes(current.id) ? item.entryIds : [...item.entryIds, current.id] } : item)); } }))); };
  const translate = motion.interpolate({ inputRange: [0, 1], outputRange: [0, 18] });
  return <ScreenContainer containerClassName="bg-[#F8F6F0]" safeAreaClassName="bg-[#F8F6F0]"><View style={styles.screen}><Animated.View pointerEvents="none" style={[styles.motifOne, { opacity: motion.interpolate({ inputRange: [0, 1], outputRange: [0.2, 0.55] }), transform: [{ translateY: translate }] }]} /><Animated.View pointerEvents="none" style={[styles.motifTwo, { opacity: motion.interpolate({ inputRange: [0, 1], outputRange: [0.45, 0.12] }), transform: [{ translateY: translate }] }]} /><Animated.View pointerEvents="none" style={[styles.motifThree, { opacity: motion.interpolate({ inputRange: [0, 1], outputRange: [0.1, 0.4] }), transform: [{ translateY: translate }] }]} /><View style={styles.top}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.circleButton, pressed && styles.pressed]}><Ionicons name="chevron-down" size={23} color={colors.ink} /></Pressable><Text style={styles.topLabel}>ŞÜKRAN DİNLİYORSUN</Text><Pressable onPress={addToPlaylist} style={({ pressed }) => [styles.circleButton, pressed && styles.pressed]} accessibilityLabel="Şükranı playlist’e ekle"><Ionicons name={current.favorite ? "star" : "star-outline"} size={20} color={colors.orange} /></Pressable><Pressable onPress={closePlayer} style={({ pressed }) => [styles.circleButton, pressed && styles.pressed]} accessibilityLabel="Oynatıcıyı kapat"><Ionicons name="close" size={20} color={colors.ink} /></Pressable></View><View style={styles.content}><Text style={styles.counter}>{currentIndex + 1} / {entries.length} · {settings.rate.toFixed(1)}x</Text><Text style={styles.heading}>Şu an minnettar olduğun şey</Text><Text style={styles.gratitude}>{current.text}</Text><View style={styles.progress}><View style={[styles.progressFill, { width: `${((currentIndex + 1) / entries.length) * 100}%` }]} /></View><View style={styles.controls}><Pressable onPress={previous} disabled={currentIndex === 0} style={({ pressed }) => [styles.skip, currentIndex === 0 && styles.disabled, pressed && styles.pressed]}><Ionicons name="play-skip-back" size={25} color={colors.ink} /></Pressable><Pressable onPress={toggle} style={({ pressed }) => [styles.mainPlay, pressed && styles.pressed]}><Ionicons name={isPlaying ? "pause" : "play"} size={29} color="#FFFFFF" /></Pressable><Pressable onPress={next} disabled={currentIndex >= entries.length - 1} style={({ pressed }) => [styles.skip, currentIndex >= entries.length - 1 && styles.disabled, pressed && styles.pressed]}><Ionicons name="play-skip-forward" size={25} color={colors.ink} /></Pressable></View><Text style={styles.hint}>{isPlaying ? "Sakin bir nefes al ve dinle" : "Devam etmek için oynat"}</Text></View></View></ScreenContainer>;
}
const styles = StyleSheet.create({ screen: { flex: 1, overflow: "hidden", paddingHorizontal: 24 }, top: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingTop: 15 }, topLabel: { color: colors.muted, fontSize: 10, fontWeight: "800", letterSpacing: 1.5 }, circleButton: { alignItems: "center", backgroundColor: colors.surface, borderRadius: 21, height: 42, justifyContent: "center", width: 42 }, content: { flex: 1, justifyContent: "center", paddingBottom: 36 }, counter: { color: colors.primary, fontSize: 11, fontWeight: "800", letterSpacing: 1, textAlign: "center" }, heading: { color: colors.muted, fontSize: 13, marginTop: 18, textAlign: "center" }, gratitude: { color: colors.ink, fontSize: 19, fontWeight: "800", lineHeight: 28, marginTop: 14, textAlign: "center" }, progress: { backgroundColor: "#DDE8E0", borderRadius: 3, height: 5, marginTop: 34, overflow: "hidden" }, progressFill: { backgroundColor: colors.primary, borderRadius: 3, height: 5 }, controls: { alignItems: "center", flexDirection: "row", justifyContent: "center", marginTop: 34 }, skip: { alignItems: "center", height: 55, justifyContent: "center", width: 60 }, mainPlay: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 31, elevation: 5, height: 62, justifyContent: "center", marginHorizontal: 20, shadowColor: colors.ink, shadowOpacity: 0.15, shadowRadius: 8, width: 62 }, hint: { color: colors.muted, fontSize: 11, marginTop: 17, textAlign: "center" }, motifOne: { backgroundColor: colors.soft, borderRadius: 75, height: 150, position: "absolute", right: -55, top: 120, width: 150 }, motifTwo: { borderColor: colors.orange, borderRadius: 44, borderWidth: 2, height: 88, left: -28, position: "absolute", top: 230, width: 88 }, motifThree: { backgroundColor: colors.orange, borderRadius: 20, bottom: 130, height: 40, position: "absolute", right: 28, width: 40 }, disabled: { opacity: 0.25 }, pressed: { opacity: 0.7, transform: [{ scale: 0.96 }] }, empty: { alignItems: "center", flex: 1, justifyContent: "center" }, emptyTitle: { color: colors.ink, fontSize: 18, fontWeight: "800" }, backAction: { backgroundColor: colors.primary, borderRadius: 14, marginTop: 16, paddingHorizontal: 18, paddingVertical: 12 }, backText: { color: "#FFFFFF", fontWeight: "800" } });
