import { useEffect, useRef, useState } from "react";
import { Animated, Pressable, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { usePlayer } from "@/lib/player-context";
import { loadGratitudeEntries, saveGratitudeEntries } from "@/lib/gratitude";
import { ensureDefaultPlaylist, savePlaylists, type Playlist } from "@/lib/playlists";
import { PlaylistPicker } from "@/components/playlist-picker";

const colors = { background: "#F8F6F0", ink: "#163B2B", muted: "#7B8A82", primary: "#2F7D5A", orange: "#E9905E", surface: "#FFFFFF" };
const motifs = ["✦", "✧", "♡", "☼", "❀", "✿", "❁", "☘", "☾", "☀", "☺", "☻", "❤", "❖", "✺", "✹", "✷", "✵", "❋", "❊", "♧", "♢", "♤", "♧", "☁", "☾", "☽", "☀", "☼", "✧", "❀", "✿", "♡", "☺", "✦", "❖", "✺", "☘", "❋", "✷"];

export default function PlayerScreen() {
  const router = useRouter();
  const { entries, currentIndex, isPlaying, settings, toggle, next, previous, hide } = usePlayer();
  const current = entries[currentIndex];
  const transition = useRef(new Animated.Value(0)).current;
  const motifPulse = useRef(new Animated.Value(0)).current;
  const [pickerOpen, setPickerOpen] = useState(false);
  const [playlists, setPlaylists] = useState<Playlist[]>([]);

  useEffect(() => { transition.setValue(0); Animated.timing(transition, { toValue: 1, duration: 260, useNativeDriver: true }).start(); }, [current?.id, transition]);
  useEffect(() => { const loop = Animated.loop(Animated.sequence([Animated.timing(motifPulse, { toValue: 1, duration: 2400, useNativeDriver: true }), Animated.timing(motifPulse, { toValue: 0, duration: 1800, useNativeDriver: true })])); loop.start(); return () => loop.stop(); }, [motifPulse, current?.id]);
  if (!current) return <ScreenContainer containerClassName="bg-[#F8F6F0]" safeAreaClassName="bg-[#F8F6F0]"><View style={styles.empty}><Text style={styles.emptyTitle}>Henüz dinlenecek şükran yok</Text><Pressable onPress={() => router.back()} style={styles.backAction}><Text style={styles.backText}>Geri dön</Text></Pressable></View></ScreenContainer>;

  const closePlayer = () => { hide(); router.back(); };
  const openPlaylistPicker = async () => { setPlaylists(await ensureDefaultPlaylist()); setPickerOpen(true); };
  const addToPlaylist = async (playlist: Playlist) => { const loaded = await loadGratitudeEntries(); const nextEntries = loaded.map((entry) => entry.id === current.id ? { ...entry, favorite: true } : entry); const nextLists = playlists.map((item) => item.id === playlist.id ? { ...item, entryIds: item.entryIds.includes(current.id) ? item.entryIds : [...item.entryIds, current.id] } : item); await saveGratitudeEntries(nextEntries); await savePlaylists(nextLists); setPickerOpen(false); };
  const createPlaylist = async (name: string) => { const loaded = await loadGratitudeEntries(); const created: Playlist = { id: `playlist-${Date.now()}`, name, entryIds: [current.id], createdAt: new Date().toISOString() }; await saveGratitudeEntries(loaded.map((entry) => entry.id === current.id ? { ...entry, favorite: true } : entry)); await savePlaylists([...playlists, created]); setPickerOpen(false); };

  const visibleMotifs = [0, 1, 2, 3].map((offset) => motifs[(currentIndex * 7 + offset * 11) % motifs.length]);
  return <ScreenContainer containerClassName="bg-[#F8F6F0]" safeAreaClassName="bg-[#F8F6F0]"><View style={styles.screen}><View pointerEvents="none" style={styles.motifLayer}>{visibleMotifs.map((motif, index) => <Animated.Text key={`${current.id}-${index}`} style={[styles.motif, { left: `${12 + index * 27}%`, top: `${16 + (index * 19) % 60}%`, opacity: motifPulse.interpolate({ inputRange: [0, 1], outputRange: [0.08, 0.32] }), transform: [{ translateY: motifPulse.interpolate({ inputRange: [0, 1], outputRange: [14, -8] }) }, { scale: motifPulse.interpolate({ inputRange: [0, 1], outputRange: [0.82, 1] }) }] }]}>{motif}</Animated.Text>)}</View><PlaylistPicker visible={pickerOpen} playlists={playlists} onClose={() => setPickerOpen(false)} onSelect={addToPlaylist} onCreate={createPlaylist} /><View style={styles.top}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.circleButton, pressed && styles.pressed]}><Ionicons name="chevron-down" size={23} color={colors.ink} /></Pressable><Text style={styles.topLabel}>ŞÜKRAN DİNLİYORSUN</Text><Pressable onPress={openPlaylistPicker} style={({ pressed }) => [styles.circleButton, pressed && styles.pressed]} accessibilityLabel="Şükranı playlist’e ekle"><Ionicons name={current.favorite ? "star" : "star-outline"} size={20} color={colors.orange} /></Pressable><Pressable onPress={closePlayer} style={({ pressed }) => [styles.circleButton, pressed && styles.pressed]} accessibilityLabel="Oynatıcıyı kapat"><Ionicons name="close" size={20} color={colors.ink} /></Pressable></View><Animated.View style={[styles.content, { opacity: transition, transform: [{ translateY: transition.interpolate({ inputRange: [0, 1], outputRange: [10, 0] }) }] }]}><Text style={styles.counter}>{currentIndex + 1} / {entries.length} · {settings.rate.toFixed(1)}x</Text><Text style={styles.heading}>Şu an minnettar olduğun şey</Text><Text style={styles.gratitude}>{current.text}</Text><View style={styles.progress}><View style={[styles.progressFill, { width: `${((currentIndex + 1) / entries.length) * 100}%` }]} /></View><View style={styles.controls}><Pressable onPress={previous} disabled={currentIndex === 0} style={({ pressed }) => [styles.skip, currentIndex === 0 && styles.disabled, pressed && styles.pressed]}><Ionicons name="play-skip-back" size={25} color={colors.ink} /></Pressable><Pressable onPress={toggle} style={({ pressed }) => [styles.mainPlay, pressed && styles.pressed]}><Ionicons name={isPlaying ? "pause" : "play"} size={29} color="#FFFFFF" /></Pressable><Pressable onPress={next} disabled={currentIndex >= entries.length - 1} style={({ pressed }) => [styles.skip, currentIndex >= entries.length - 1 && styles.disabled, pressed && styles.pressed]}><Ionicons name="play-skip-forward" size={25} color={colors.ink} /></Pressable></View><Text style={styles.hint}>{isPlaying ? "Şükranın okunuyor" : "Devam etmek için oynat"}</Text></Animated.View></View></ScreenContainer>;
}

const styles = StyleSheet.create({ screen: { backgroundColor: colors.background, flex: 1, overflow: "hidden", paddingHorizontal: 24 }, motifLayer: { ...StyleSheet.absoluteFillObject }, motif: { color: colors.primary, fontSize: 210, position: "absolute" }, top: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingTop: 15 }, topLabel: { color: colors.muted, fontSize: 10, fontWeight: "800", letterSpacing: 1.5 }, circleButton: { alignItems: "center", backgroundColor: colors.surface, borderRadius: 21, height: 42, justifyContent: "center", width: 42 }, content: { flex: 1, justifyContent: "center", paddingBottom: 36 }, counter: { color: colors.primary, fontSize: 11, fontWeight: "800", letterSpacing: 1, textAlign: "center" }, heading: { color: colors.muted, fontSize: 13, marginTop: 18, textAlign: "center" }, gratitude: { color: colors.ink, fontSize: 19, fontWeight: "800", lineHeight: 29, marginTop: 30, textAlign: "center" }, progress: { backgroundColor: "#DDE8E0", borderRadius: 3, height: 5, marginTop: 30, overflow: "hidden" }, progressFill: { backgroundColor: colors.primary, borderRadius: 3, height: 5 }, controls: { alignItems: "center", flexDirection: "row", justifyContent: "center", marginTop: 27 }, skip: { alignItems: "center", height: 55, justifyContent: "center", width: 60 }, mainPlay: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 31, elevation: 5, height: 62, justifyContent: "center", marginHorizontal: 20, shadowColor: colors.ink, shadowOpacity: 0.15, shadowRadius: 8, width: 62 }, hint: { color: colors.muted, fontSize: 11, marginTop: 17, textAlign: "center" }, disabled: { opacity: 0.25 }, pressed: { opacity: 0.7, transform: [{ scale: 0.96 }] }, empty: { alignItems: "center", flex: 1, justifyContent: "center" }, emptyTitle: { color: colors.ink, fontSize: 18, fontWeight: "800" }, backAction: { backgroundColor: colors.primary, borderRadius: 14, marginTop: 16, paddingHorizontal: 18, paddingVertical: 12 }, backText: { color: "#FFFFFF", fontWeight: "800" } });
