import { useEffect, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import type { Playlist } from "@/lib/playlists";

type Props = { visible: boolean; playlists: Playlist[]; onClose: () => void; onSelect: (playlist: Playlist) => void; onCreate: (name: string) => void };

export function PlaylistPicker({ visible, playlists, onClose, onSelect, onCreate }: Props) {
  const [createOpen, setCreateOpen] = useState(false); const [name, setName] = useState("");
  useEffect(() => { if (!visible) { setCreateOpen(false); setName(""); } }, [visible]);
  const create = () => { const value = name.trim(); if (!value) return; onCreate(value); setName(""); setCreateOpen(false); };
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.modal}><View style={styles.header}><View><Text style={styles.eyebrow}>ŞÜKRANI SAKLA</Text><Text style={styles.title}>Hangi playlist’e ekleyelim?</Text></View><Pressable onPress={onClose} style={styles.close}><Ionicons name="close" size={18} color="#163B2B" /></Pressable></View>{createOpen ? <View><TextInput autoFocus value={name} onChangeText={setName} placeholder="Playlist adı" placeholderTextColor="#9BA7A0" style={styles.input} returnKeyType="done" onSubmitEditing={create} /><View style={styles.row}><Pressable onPress={() => setCreateOpen(false)} style={styles.cancel}><Text style={styles.cancelText}>Vazgeç</Text></Pressable><Pressable onPress={create} style={styles.create}><Text style={styles.createText}>Oluştur</Text></Pressable></View></View> : <ScrollView style={styles.playlistScroll} showsVerticalScrollIndicator={false}><Pressable onPress={() => setCreateOpen(true)} style={styles.newButton}><Ionicons name="add-circle-outline" size={20} color="#2F7D5A" /><Text style={styles.newText}>Yeni playlist oluştur</Text></Pressable>{playlists.map((playlist) => <Pressable key={playlist.id} onPress={() => onSelect(playlist)} style={({ pressed }) => [styles.playlist, pressed && styles.pressed]}><View style={styles.icon}><Ionicons name="musical-notes" size={16} color="#2F7D5A" /></View><Text style={styles.playlistName}>{playlist.name}</Text><Ionicons name="chevron-forward" size={18} color="#9BA7A0" /></Pressable>)}</ScrollView>}</View></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { alignItems: "center", backgroundColor: "rgba(22,59,43,0.38)", flex: 1, justifyContent: "center", padding: 22 }, modal: { backgroundColor: "#F8F6F0", borderRadius: 22, maxHeight: "70%", padding: 20, width: "100%" }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 15 }, eyebrow: { color: "#2F7D5A", fontSize: 9, fontWeight: "800", letterSpacing: 1.3 }, title: { color: "#163B2B", fontSize: 18, fontWeight: "800", marginTop: 4 }, close: { alignItems: "center", backgroundColor: "#FFFFFF", borderRadius: 18, height: 36, justifyContent: "center", width: 36 }, playlistScroll: { flexGrow: 0 }, newButton: { alignItems: "center", backgroundColor: "#E1F0E8", borderRadius: 13, flexDirection: "row", gap: 9, marginBottom: 10, padding: 13 }, newText: { color: "#2F7D5A", fontSize: 13, fontWeight: "800" }, playlist: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E6E8E2", borderRadius: 13, borderWidth: 1, flexDirection: "row", marginBottom: 8, padding: 12 }, icon: { alignItems: "center", backgroundColor: "#E1F0E8", borderRadius: 15, height: 30, justifyContent: "center", width: 30 }, playlistName: { color: "#163B2B", flex: 1, fontSize: 13, fontWeight: "700", marginLeft: 9 }, input: { backgroundColor: "#FFFFFF", borderColor: "#E6E8E2", borderRadius: 12, borderWidth: 1, color: "#163B2B", fontSize: 15, height: 50, paddingHorizontal: 13 }, row: { flexDirection: "row", gap: 9, justifyContent: "flex-end", marginTop: 13 }, cancel: { borderColor: "#E6E8E2", borderRadius: 11, borderWidth: 1, paddingHorizontal: 15, paddingVertical: 11 }, cancelText: { color: "#7B8A82", fontWeight: "800" }, create: { backgroundColor: "#2F7D5A", borderRadius: 11, paddingHorizontal: 17, paddingVertical: 11 }, createText: { color: "#FFFFFF", fontWeight: "800" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
