import type { GratitudeEntry } from "@/lib/gratitude";
export type Badge = { id: string; icon: string; title: string; description: string; unlocked: boolean };
function dayKey(date: Date) { return `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`; }
export function getDistinctDayCount(entries: GratitudeEntry[]) { return new Set(entries.map((entry) => dayKey(new Date(entry.createdAt)))).size; }
export function getCurrentStreak(entries: GratitudeEntry[]) { const days = new Set(entries.map((entry) => dayKey(new Date(entry.createdAt)))); const cursor = new Date(); cursor.setHours(0, 0, 0, 0); let streak = 0; while (days.has(dayKey(cursor))) { streak += 1; cursor.setDate(cursor.getDate() - 1); } return streak; }
const badgeDefinitions: [string, string, string, string][] = [
  ["first", "sparkles-outline", "İlk kıvılcım", "İlk kaydını yaz"], ["three", "leaf-outline", "Filiz", "3 kayıt oluştur"], ["five", "heart-outline", "Kalp sesi", "5 kayıt oluştur"], ["ten", "star-outline", "Kıvılcım", "10 kayıt oluştur"], ["fifteen", "sunny-outline", "Güneşli gün", "15 kayıt oluştur"], ["twenty", "flower-outline", "Çiçeklenme", "20 kayıt oluştur"], ["thirty", "ribbon-outline", "İlk kurdele", "30 kayıt oluştur"], ["fifty", "diamond-outline", "Parlayan taş", "50 kayıt oluştur"], ["hundred", "trophy-outline", "Yüz ışık", "100 kayıt oluştur"], ["twohundred", "medal-outline", "Sabır madalyası", "200 kayıt oluştur"],
  ["day1", "today-outline", "Bugünün sesi", "Bugün yaz"], ["days3", "calendar-outline", "Üç gün", "3 farklı günde yaz"], ["days7", "calendar-number-outline", "Hafta ritmi", "7 farklı günde yaz"], ["days14", "time-outline", "İki haftalık iz", "14 farklı günde yaz"], ["days30", "map-outline", "Takvim gezgini", "30 farklı günde yaz"], ["days60", "navigate-outline", "Rota ustası", "60 farklı günde yaz"], ["days100", "flag-outline", "Yüz durak", "100 farklı günde yaz"], ["streak3", "flame-outline", "Üçlü seri", "3 gün seri yap"], ["streak7", "flame", "Alev alan ritim", "7 gün seri yap"], ["streak21", "rocket-outline", "Ritim roketi", "21 gün seri yap"],
  ["streak30", "planet-outline", "Ayın ritmi", "30 gün seri yap"], ["early", "sunrise-outline", "Güne erken", "Sabah kaydı ekle"], ["night", "moon-outline", "Gece düşüncesi", "Gece kaydı ekle"], ["weekend", "cafe-outline", "Hafta sonu", "Hafta sonu yaz"], ["monday", "refresh-outline", "Yeni hafta", "Pazartesi yaz"], ["listener", "volume-high-outline", "Dinleyen kalp", "Bir kaydı dinle"], ["listener10", "headset-outline", "Kulak veren", "10 kayıt dinle"], ["playlist", "musical-notes-outline", "Küratör", "Playlist oluştur"], ["playlists3", "albums-outline", "Arşivci", "3 playlist oluştur"], ["favorite", "star", "Seçici kalp", "Bir kaydı favorile"],
  ["goal", "locate-outline", "Hedefe varış", "Günlük hedefi tamamla"], ["goal3", "checkmark-done-outline", "Üç hedef", "3 günlük hedef tamamla"], ["goal7", "checkmark-circle-outline", "Hedef ustası", "7 günlük hedef tamamla"], ["overflow", "trending-up-outline", "Sınırı aşan", "Hedefini aş"], ["export", "share-outline", "Anı taşıyıcı", "Yedek dışa aktar"], ["theme", "color-palette-outline", "Renk koleksiyoncusu", "Tema değiştir"], ["profile", "person-circle-outline", "Kendini tanı", "Profilini düzenle"], ["search", "search-outline", "Arşiv kâşifi", "Geçmişte ara"], ["random", "shuffle-outline", "Sürpriz seçici", "Rastgele dinle"], ["edit", "create-outline", "İnce dokunuş", "Bir kaydı düzenle"],
  ["morning", "partly-sunny-outline", "Sabah ışığı", "Sabah 5 kayıt ekle"], ["evening", "cloudy-night-outline", "Akşam huzuru", "Akşam 5 kayıt ekle"], ["long", "hourglass-outline", "Uzun soluk", "30 günde yaz"], ["variety", "grid-outline", "Çeşitlilik", "5 farklı günde yaz"], ["kindness", "people-outline", "İnsan sıcaklığı", "Bir kişiye şükret"], ["nature", "water-outline", "Doğa farkındalığı", "Doğayla ilgili yaz"], ["self", "happy-outline", "Kendine şefkat", "Kendinle ilgili yaz"], ["memory", "images-outline", "Anı kutusu", "Bir anı yaz"], ["king", "shield-checkmark-outline", "Şükür ustası", "1260 kayda ulaş"], ["master", "infinite-outline", "Sonsuz minnet", "5000 kayda ulaş"],
];
export function getBadges(entries: GratitudeEntry[]): Badge[] { const count = entries.length; const days = getDistinctDayCount(entries); const streak = getCurrentStreak(entries); return badgeDefinitions.map(([id, icon, title, description]) => ({ id, icon, title, description, unlocked: id === "first" ? count >= 1 : id === "three" ? count >= 3 : id === "five" ? count >= 5 : id === "ten" ? count >= 10 : id === "fifteen" ? count >= 15 : id === "twenty" ? count >= 20 : id === "thirty" ? count >= 30 : id === "fifty" ? count >= 50 : id === "hundred" ? count >= 100 : id === "twohundred" ? count >= 200 : id === "days3" ? days >= 3 : id === "days7" ? days >= 7 : id === "days14" ? days >= 14 : id === "days30" ? days >= 30 : id === "days60" ? days >= 60 : id === "days100" ? days >= 100 : id === "streak3" ? streak >= 3 : id === "streak7" ? streak >= 7 : id === "streak21" ? streak >= 21 : id === "streak30" ? streak >= 30 : id === "king" ? count >= 1260 : id === "master" ? count >= 5000 : id === "goal" ? count >= 5 : id === "goal3" ? count >= 15 : id === "goal7" ? count >= 35 : id === "overflow" ? count >= 6 : id === "playlist" ? false : id === "playlists3" ? false : id === "favorite" ? entries.some((entry) => entry.favorite) : id === "first" ? count >= 1 : count > 0 })); }
export function getJourneyStep(count: number) { const steps = [{ title: "Başlangıç bahçesi", min: 0, icon: "leaf-outline" }, { title: "Farkındalık yolu", min: 10, icon: "walk-outline" }, { title: "Işık vadisi", min: 90, icon: "sunny-outline" }, { title: "Minnet zirvesi", min: 360, icon: "mountain-outline" }, { title: "Şükür sarayı", min: 1260, icon: "business-outline" }]; return steps.map((step, index) => ({ ...step, index, unlocked: count >= step.min, active: count >= step.min && (index === steps.length - 1 || count < steps[index + 1].min) })); }
