import { useCallback, useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { AppTopActions } from "@/components/app-top-actions";
import { loadGratitudeEntries, type GratitudeEntry } from "@/lib/gratitude";
import { entriesForPlaylist, ensureDefaultPlaylist, savePlaylists, type Playlist } from "@/lib/playlists";
import { usePlayer } from "@/lib/player-context";

export default function FavoritesScreen() {
  const [entries, setEntries] = useState<GratitudeEntry[]>([]); const [playlists, setPlaylists] = useState<Playlist[]>([]); const [query, setQuery] = useState(""); const { playEntries } = usePlayer(); const router = useRouter();
  const refresh = useCallback(async () => { const [loaded, lists] = await Promise.all([loadGratitudeEntries(), ensureDefaultPlaylist()]); setEntries(loaded); setPlaylists(lists); }, []);
  useFocusEffect(useCallback(() => { refresh(); }, [refresh]));
  const favorites = useMemo(() => entries.filter((entry) => entry.favorite && entry.text.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))), [entries, query]);
  const createPlaylist = () => Alert.prompt?.("Yeni playlist", "Playlist adı", async (name) => { if (!name?.trim()) return; const next = [...playlists, { id: `playlist-${Date.now()}`, name: name.trim(), entryIds: [], createdAt: new Date().toISOString() }]; setPlaylists(next); await savePlaylists(next); });
  return <ScreenContainer containerClassName="bg-[#F8F6F0]"><View style={styles.header}><View><Text style={styles.eyebrow}>KÜTÜPHANEN</Text><Text style={styles.title}>Favoriler</Text></View><AppTopActions /></View><TextInput value={query} onChangeText={setQuery} placeholder="Favorilerde ara..." placeholderTextColor="#9BA7A0" style={styles.search} /><View style={styles.actions}><Pressable onPress={() => playEntries(favorites)} disabled={!favorites.length} style={styles.primary}><Ionicons name="play" size={15} color="#FFFFFF" /><Text style={styles.primaryText}>Tümünü dinle</Text></Pressable><Pressable onPress={createPlaylist} style={styles.secondary}><Ionicons name="add" size={17} color="#2F7D5A" /><Text style={styles.secondaryText}>Playlist oluştur</Text></Pressable></View><FlatList data={playlists} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={<Text style={styles.section}>Playlistler</Text>} renderItem={({ item }) => { const list = entriesForPlaylist(entries, item); return <Pressable onPress={() => router.push(`/playlist/${item.id}`)} style={styles.playlist}><View style={styles.playIcon}><Ionicons name="musical-notes" size={18} color="#2F7D5A" /></View><View style={styles.copy}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{list.length} şükran</Text></View><Ionicons name="chevron-forward" size={18} color="#9BA7A0" /></Pressable>; }} ListFooterComponent={<View><Text style={styles.section}>Favori kayıtlar</Text>{favorites.length ? favorites.map((item) => <View key={item.id} style={styles.entry}><Ionicons name="star" size={16} color="#E9905E" /><Text style={styles.entryText}>{item.text}</Text></View>) : <Text style={styles.empty}>Henüz favori şükranın yok.</Text>}</View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ header:{alignItems:"center",flexDirection:"row",justifyContent:"space-between",padding:22,paddingBottom:12},eyebrow:{color:"#2F7D5A",fontSize:10,fontWeight:"800",letterSpacing:1.4},title:{color:"#163B2B",fontSize:30,fontWeight:"800",marginTop:4},search:{backgroundColor:"#FFFFFF",borderColor:"#E6E8E2",borderRadius:14,borderWidth:1,color:"#163B2B",fontSize:14,marginHorizontal:22,padding:14},actions:{flexDirection:"row",gap:9,padding:22,paddingBottom:8},primary:{alignItems:"center",backgroundColor:"#2F7D5A",borderRadius:13,flex:1,flexDirection:"row",gap:6,justifyContent:"center",padding:13},primaryText:{color:"#FFFFFF",fontWeight:"800",fontSize:12},secondary:{alignItems:"center",backgroundColor:"#E1F0E8",borderRadius:13,flex:1,flexDirection:"row",gap:5,justifyContent:"center",padding:13},secondaryText:{color:"#2F7D5A",fontWeight:"800",fontSize:12},list:{padding:22,paddingTop:8},section:{color:"#163B2B",fontSize:17,fontWeight:"800",marginBottom:10,marginTop:12},playlist:{alignItems:"center",backgroundColor:"#FFFFFF",borderColor:"#E6E8E2",borderRadius:17,borderWidth:1,flexDirection:"row",marginBottom:9,padding:13},playIcon:{alignItems:"center",backgroundColor:"#E1F0E8",borderRadius:17,height:34,justifyContent:"center",width:34},copy:{flex:1,marginLeft:10},name:{color:"#163B2B",fontSize:14,fontWeight:"800"},meta:{color:"#7B8A82",fontSize:11,marginTop:3},entry:{alignItems:"center",backgroundColor:"#FFF9F3",borderRadius:13,flexDirection:"row",gap:9,marginBottom:7,padding:12},entryText:{color:"#163B2B",flex:1,fontSize:12},empty:{color:"#7B8A82",fontSize:12,paddingVertical:12}}
); 
