import { useCallback, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { AppTopActions } from "@/components/app-top-actions";
import { ensureDefaultPlaylist, savePlaylists, type Playlist } from "@/lib/playlists";

export default function FavoritesScreen() {
  const [playlists, setPlaylists] = useState<Playlist[]>([]); const [createOpen, setCreateOpen] = useState(false); const [name, setName] = useState(""); const router = useRouter();
  const refresh = useCallback(async () => setPlaylists(await ensureDefaultPlaylist()), []); useFocusEffect(useCallback(() => { refresh(); }, [refresh]));
  const create = async () => { const value = name.trim(); if (!value) return; const next = [...playlists, { id: `playlist-${Date.now()}`, name: value, entryIds: [], createdAt: new Date().toISOString() }]; await savePlaylists(next); setPlaylists(next); setName(""); setCreateOpen(false); };
  return <ScreenContainer containerClassName="bg-[#F8F6F0]"><ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}><View style={styles.header}><View><Text style={styles.eyebrow}>KÜTÜPHANEN</Text><Text style={styles.title}>Favoriler</Text></View><AppTopActions /></View><Pressable onPress={() => setCreateOpen(true)} style={styles.createButton}><Ionicons name="add-circle-outline" size={20} color="#FFFFFF" /><Text style={styles.createText}>Playlist oluştur</Text></Pressable><Text style={styles.section}>Playlistler</Text><View style={styles.list}>{playlists.map((item) => <Pressable key={item.id} onPress={() => router.push(`/playlist/${item.id}`)} style={({ pressed }) => [styles.playlist, pressed && styles.pressed]}><View style={styles.playIcon}><Ionicons name="musical-notes" size={18} color="#2F7D5A" /></View><View style={styles.copy}><Text style={styles.playName}>{item.name}</Text><Text style={styles.meta}>{item.entryIds.length} şükran</Text></View><Ionicons name="chevron-forward" size={18} color="#9BA7A0" /></Pressable>)}</View></ScrollView><Modal visible={createOpen} transparent animationType="fade" onRequestClose={() => setCreateOpen(false)}><View style={styles.backdrop}><View style={styles.modal}><Text style={styles.eyebrow}>YENİ PLAYLİST</Text><Text style={styles.modalTitle}>Playlistine bir isim ver</Text><TextInput autoFocus value={name} onChangeText={setName} placeholder="Örn. Küçük mutluluklar" placeholderTextColor="#9BA7A0" style={styles.input} returnKeyType="done" onSubmitEditing={create} /><View style={styles.modalActions}><Pressable onPress={() => setCreateOpen(false)} style={styles.cancel}><Text style={styles.cancelText}>Vazgeç</Text></Pressable><Pressable onPress={create} style={styles.save}><Text style={styles.saveText}>Oluştur</Text></Pressable></View></View></View></Modal></ScreenContainer>;
}
const styles = StyleSheet.create({ scrollContent: { paddingBottom: 40 }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", padding: 22, paddingBottom: 12 }, eyebrow: { color: "#2F7D5A", fontSize: 10, fontWeight: "800", letterSpacing: 1.4 }, title: { color: "#163B2B", fontSize: 30, fontWeight: "800", marginTop: 4 }, createButton: { alignItems: "center", backgroundColor: "#2F7D5A", borderRadius: 15, flexDirection: "row", gap: 8, justifyContent: "center", marginHorizontal: 22, padding: 14 }, createText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" }, section: { color: "#163B2B", fontSize: 18, fontWeight: "800", marginHorizontal: 22, marginTop: 25 }, list: { padding: 22, paddingTop: 12 }, playlist: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E6E8E2", borderRadius: 17, borderWidth: 1, flexDirection: "row", marginBottom: 9, padding: 13 }, playIcon: { alignItems: "center", backgroundColor: "#E1F0E8", borderRadius: 17, height: 34, justifyContent: "center", width: 34 }, copy: { flex: 1, marginLeft: 10 }, playName: { color: "#163B2B", fontSize: 14, fontWeight: "800" }, meta: { color: "#7B8A82", fontSize: 11, marginTop: 3 }, backdrop: { alignItems: "center", backgroundColor: "rgba(22,59,43,0.38)", flex: 1, justifyContent: "center", padding: 22 }, modal: { backgroundColor: "#F8F6F0", borderRadius: 21, padding: 20, width: "100%" }, modalTitle: { color: "#163B2B", fontSize: 18, fontWeight: "800", marginTop: 5 }, input: { backgroundColor: "#FFFFFF", borderColor: "#E6E8E2", borderRadius: 12, borderWidth: 1, color: "#163B2B", fontSize: 14, height: 50, marginTop: 16, paddingHorizontal: 12 }, modalActions: { flexDirection: "row", gap: 9, justifyContent: "flex-end", marginTop: 16 }, cancel: { borderColor: "#E6E8E2", borderRadius: 10, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 10 }, cancelText: { color: "#7B8A82", fontWeight: "800" }, save: { backgroundColor: "#2F7D5A", borderRadius: 10, paddingHorizontal: 16, paddingVertical: 10 }, saveText: { color: "#FFFFFF", fontWeight: "800" }, pressed: { opacity: 0.75, transform: [{ scale: 0.98 }] } });
