import { useCallback, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useFocusEffect, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { loadGratitudeEntries, type GratitudeEntry } from "@/lib/gratitude";
import { entriesForPlaylist, loadPlaylists, savePlaylists, type Playlist } from "@/lib/playlists";
import { usePlayer } from "@/lib/player-context";
export default function PlaylistDetail() { const { id } = useLocalSearchParams<{ id: string }>(); const [playlist, setPlaylist] = useState<Playlist | null>(null); const [entries, setEntries] = useState<GratitudeEntry[]>([]); const { playEntries } = usePlayer(); const router = useRouter(); const refresh = useCallback(async () => { const [lists, loaded] = await Promise.all([loadPlaylists(), loadGratitudeEntries()]); setPlaylist(lists.find((item) => item.id === id) ?? null); setEntries(loaded); }, [id]); useFocusEffect(useCallback(() => { refresh(); }, [refresh])); const list = playlist ? entriesForPlaylist(entries, playlist) : []; const rename = () => Alert.prompt?.("Playlist adını değiştir", "Yeni ad", async (name) => { if (!name?.trim() || !playlist) return; const lists = await loadPlaylists(); const next = lists.map((item) => item.id === playlist.id ? { ...item, name: name.trim() } : item); await savePlaylists(next); setPlaylist({ ...playlist, name: name.trim() }); }); return <ScreenContainer containerClassName="bg-[#F8F6F0]"><View style={styles.header}><Pressable onPress={() => router.back()}><Ionicons name="chevron-back" size={24} color="#163B2B" /></Pressable><View style={styles.titleWrap}><Text style={styles.eyebrow}>PLAYLIST</Text><Text style={styles.title}>{playlist?.name ?? "Playlist"}</Text></View><Pressable onPress={rename}><Ionicons name="pencil-outline" size={20} color="#2F7D5A" /></Pressable></View><Pressable onPress={() => playEntries(list)} disabled={!list.length} style={styles.play}><Ionicons name="play" size={17} color="#FFFFFF" /><Text style={styles.playText}>Tümünü dinle</Text></Pressable><FlatList data={list} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item, index }) => <View style={styles.entry}><Text style={styles.number}>{String(index + 1).padStart(2, "0")}</Text><Text style={styles.entryText}>{item.text}</Text><Ionicons name="star" size={16} color="#E9905E" /></View>} ListEmptyComponent={<Text style={styles.empty}>Bu playlist henüz boş.</Text>} /></ScreenContainer>; }
const styles=StyleSheet.create({header:{alignItems:"center",flexDirection:"row",gap:12,padding:22},titleWrap:{flex:1},eyebrow:{color:"#2F7D5A",fontSize:9,fontWeight:"800",letterSpacing:1.3},title:{color:"#163B2B",fontSize:25,fontWeight:"800",marginTop:3},play:{alignItems:"center",backgroundColor:"#2F7D5A",borderRadius:14,flexDirection:"row",gap:7,justifyContent:"center",marginHorizontal:22,padding:14},playText:{color:"#FFFFFF",fontWeight:"800"},list:{padding:22},entry:{alignItems:"center",backgroundColor:"#FFFFFF",borderColor:"#E6E8E2",borderRadius:15,borderWidth:1,flexDirection:"row",gap:10,marginBottom:8,padding:13},number:{color:"#2F7D5A",fontWeight:"800",width:25},entryText:{color:"#163B2B",flex:1,fontSize:13},empty:{color:"#7B8A82",padding:22}}
);
